[package]
name = "tokyo-times"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew.git" }
reqwasm = "0.5"
serde = "1.0"
serde_json = "1.0"
