use yew::prelude::*;
pub mod api;
pub mod components;
pub mod router;
pub mod routes;
use router::Router;

// NOTE: Declares a function component.
// Inputs: props.
// Outputs: Html, generated by the `Html` macro.
#[function_component]
fn App() -> Html {
    html! {
        <Router />
    }
}

fn main() {
    // NOTE: Render the `App` component:
    yew::Renderer::<App>::new().render();
}
