name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Or your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Trunk
        run: cargo install trunk
      - name: Build Yew App
        run: "trunk build --release && bun run build"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
          name: build-artifact
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
