name: Deploy to GitHub Pages

on:
  push:
    branches: [master] # Or your main branch
  pull_request:
    branches: [master] # Or your main branch

jobs:
tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
    - name: Build and deploy
      shell: devenv shell bash -- -e {0}
      run: |
        deploy
